image: docker:27-cli

services:
  - name: docker:27-dind
    alias: docker

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - test

test_website:
  stage: test

  before_script:
    - apk add --no-cache curl

  script:
    - docker version

    - docker build -t berik-devops-web:test .

    - docker run -d --name test-web -p 8080:80 berik-devops-web:test

    - sleep 3

    - curl --fail http://docker:8080
    - curl -s http://docker:8080 | grep "Berik DevOps Lab"
    - curl -s http://docker:8080 | grep "Application status: ONLINE"

  after_script:
    - docker rm -f test-web || true
