image: docker:27-cli

services:
  - name: docker:27-dind
    alias: docker

variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - publish
  - deploy


test_website:
  stage: test

  before_script:
    - export DOCKER_HOST="tcp://docker:2375"
    - apk add --no-cache curl
    - docker info

  script:
    - docker build -t berik-devops-web:test .
    - docker run -d --name test-web -p 8080:80 berik-devops-web:test
    - sleep 3

    - |
      curl --fail http://docker:8080

    - |
      curl -s http://docker:8080 | grep "Berik DevOps Lab"

    - |
      curl -s http://docker:8080 | grep "Application status: ONLINE"

  after_script:
    - export DOCKER_HOST="tcp://docker:2375"
    - docker rm -f test-web || true


publish_image:
  stage: publish

  before_script:
    - export DOCKER_HOST="tcp://docker:2375"
    - docker info

  script:
    - |
      echo "$CI_REGISTRY_PASSWORD" | docker login \
      -u "$CI_REGISTRY_USER" \
      --password-stdin "$CI_REGISTRY"

    - |
      docker build \
      -t "$CI_REGISTRY_IMAGE:latest" \
      -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" \
      .

    - docker push "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


deploy_server2:
  stage: deploy

  tags:
    - server2-deploy

  before_script:
    - export DOCKER_HOST="unix:///var/run/docker.sock"
    - docker info

  script:
    - |
      echo "$CI_REGISTRY_PASSWORD" | docker login \
      -u "$CI_REGISTRY_USER" \
      --password-stdin "$CI_REGISTRY"

    - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"

    - docker rm -f berik-web || true

    - |
      docker run -d \
      --name berik-web \
      --restart unless-stopped \
      -p 8080:80 \
      "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"

    - sleep 3
    - curl --fail http://127.0.0.1:8080
    - docker ps --filter name=berik-web

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

rollback_server2:
  stage: deploy

  tags:
    - server2-deploy

  variables:
    DOCKER_HOST: "unix:///var/run/docker.sock"
    ROLLBACK_TAG: "53cd2321"

  script:
    - |
      echo "$CI_REGISTRY_PASSWORD" | docker login \
      -u "$CI_REGISTRY_USER" \
      --password-stdin "$CI_REGISTRY"

    - docker pull "$CI_REGISTRY_IMAGE:$ROLLBACK_TAG"

    - docker rm -f berik-web || true

    - |
      docker run -d \
      --name berik-web \
      --restart unless-stopped \
      -p 8080:80 \
      "$CI_REGISTRY_IMAGE:$ROLLBACK_TAG"

    - docker ps --filter name=berik-web

  when: manual
  allow_failure: true

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
